// export const = '' ;
export const SET_ACCOUNTS= 'SET_ACCOUNTS' ;
export const INIT_ACCOUNTS= 'INIT_ACCOUNTS' ;

export const SET_GROUPS= 'SET_GROUPS' ;
export const INIT_GROUPS= 'INIT_GROUPS' ;

export const TOOGLE_ACCOUNTS_EDIT_MODE = 'TOOGLE_ACCOUNTS_EDIT_MODE' ;

export const SET_TRANSFERS= 'SET_TRANSFERS' ;
export const INIT_TRANSFERS= 'INIT_TRANSFERS' ;

export const SET_CATEGORIES= 'SET_CATEGORIES' ;
export const INIT_CATEGORIES= 'INIT_CATEGORIES' ;